// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhFrTt-xDBN3gsqhyQ_WR6eMmkmea6CJc',
    appId: '1:517809530409:web:ecca53f31f98ee398cde38',
    messagingSenderId: '517809530409',
    projectId: 'farmoish-flutter',
    authDomain: 'farmoish-flutter.firebaseapp.com',
    storageBucket: 'farmoish-flutter.firebasestorage.app',
    measurementId: 'G-C93Z15NZEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj5IlZVhM7keClPR6LKHSAJh5U60Ntycg',
    appId: '1:517809530409:android:106ccfbd8d1062468cde38',
    messagingSenderId: '517809530409',
    projectId: 'farmoish-flutter',
    storageBucket: 'farmoish-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDWZoU3pA0Et-6kwaJexVW6Zkj3o36EmE',
    appId: '1:517809530409:ios:1fe8cde653d060248cde38',
    messagingSenderId: '517809530409',
    projectId: 'farmoish-flutter',
    storageBucket: 'farmoish-flutter.firebasestorage.app',
    iosBundleId: 'com.example.farmoish',
  );
}
